### ISSUE TITLE
Remove repos property from config.yml

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#163]
Improve current implementation so criteria properties are in accordance with the concepts being represented:
- projects (software or platforms)
- build tools

So the expected result would allow to change from:
```
sqa_criteria:
  qc_style:
    commands: [ ..]
    repos:
      whatever-project-id:
        commands: [ .. ]
```

into one of the following representations:
- in case there is only one project to be tested
```
sqa_criteria:
  qc_style:
    builders:
      - commands: [ ..]
      - tox: [...]
      - maven: [...]
```

- if there is more than one project to test:
```
sqa_criteria:
  whatever-project-id:
    qc_style:
      builders:
        - commands: [ ..]
        - tox: [...]
        - maven: [...]
```
