### ISSUE TITLE
Support generic stages labels

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#164]
As an improvement from previous release, JePL will support a special case for defining the composer responsible for the deployment and docker-registry operations on specific stages.
For this a set of properties are expected for each one:
- by default will always run the following deployment to assure regression testing and backward compatibility
```
deployment:
  composer: 'docker-compose'
  configuration: './.sqa/docker-compose.yml'
```
- docker registry support in specific stage
```
docker_registry:
  services:
    - service1
    - service2
  options:
    ignore_push_failures: 'false'
```

The challenge here is to understand if is possible to use any name for the property "deployment" and "docker_registry", without requiring specific prefix.

In the end, such deployment as docker_registry can appear in any position when defining the pipeline configuration, but with the requirement that the deployment only applies to the following projects and docker-registry always needs a previous deployment:
```
deployment0:
  composer: 'infrastructure manager'
  configuration: './.im/infra.tosca'

deployment1:
  composer: 'docker-compose'
  configuration: './.sqa/docker-compose.yml'

whatever-project-id1:
  sqa_criteria:
    qc_style:
      builders:
        - commands: [ ..]
        - tox: [...]
        - maven: [...]

docker_registry1:
  services:
    - service1
    - service2
  options:
    ignore_push_failures: 'false'

deployment3:
  composer: 'kubernetes'
  configs:
    - './k8s'
  options:
    template: 'false'
    kustomize: 'true'
    helm: 'false'
    apply: 'true'

whatever-project-id2:
  sqa_criteria:
    qc_style:
      builders:
        - commands: [ ..]
        - tox: [...]
        - maven: [...]

docker_registry2:
  services:
    - service1
    - service2
  options:
    ignore_push_failures: 'false'
```

**Comment by orviz** [comment]
@samuelbernardolip how are the services/deployments aligned with the 1) criteria and 2) registries? So far we have the `container` property (inside the criteria) to point to the service from the deployment. The deployment is unique so there is no need to refer to it. With this approach, we need to both define the service and the deployment, how do you expect to do that?

**Comment by samuelbernardolip** [comment]
> how are the services/deployments aligned with the 1) criteria and 2) registries?

Building the required layers:
1- get the deployment with all the required services
2- run the criteria defined operations over the deployment
3- push the images to the registry

Step 3 don't depend on 2, but 2 and 3 depend on 1.

> So far we have the `container` property (inside the criteria) to point to the service from the deployment. The deployment is unique so there is no need to refer to it. With this approach, we need to both define the service and the deployment, how do you expect to do that?

The container property is a hack in previous release to have this feature available as soon as possible. With this new approach all concepts become part of the configuration description and solves the limitation of the phantom docker operations stage in the end. With this proposal becomes possible to define the stage where desired.

The deployment have the current default using docker-compose.yml for DockerCompose composer. With other composers the default should also be defined and if not it should fail if required. So in the end, if a deployment stage doesn't exists, JePL will try the defaults as it happens in current release 2.1.0.

**Comment by samuelbernardolip** [comment]
@orviz as we review in our meeting the implemented solution will follow the next syntax:

```
configs:
 credentials:
  sadkfjlkas
 deployments:
  asdfasdfa1:
    composer: 'kubernetes'
    configs:
    - './k8s'
    options:
     template: 'false'
     kustomize: 'true'
     helm: 'false'
     apply: 'true'
    commands:
     - im $sakldal
     - kubespray
 container_groups:
   groupA:
	services:
    - service1
    - service2
    options:
    ignore_push_failures: 'false'
 
 
 sqa_criteria:
    qc_style:
      repos:
        repoA_c1:
		 deployment:
		  name: asdfasdfa1
          service: c1
          push: groupA
		 commands: [ ..]
		 tox: [...]
		 maven: [...]
	    repoA_c2:
		 deployment:
		  name: asdfasdfa1
          service: c2
          push: groupA
		 commands: [ ..]
		 tox: [...]
		 maven: [...]
    
	qc_delivery:
	  repos:
       repoA:
         deployment:
          name: asdfasdfa1
          push: groupA
          cleanup: true
```

There are other improvements to ignore failures by stages, besides complete pipeline, that will be not merged now.
Issue #163, related to remove repos property, will not be implemented with current proposal.
Generic labels approach _whatever-project-id2_ will be left for later review, keeping now with only two main properties as _configs:_ and  _sqa_criteria:_ to pass regression testing on this phase. For the same reason, the support of _builders:_ property will also be left here for later improvement, so JePL supports previous release configuration syntax and we can keep working on release 2.
