### ISSUE TITLE
docker-compose up don't respect pull policy

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#177]
Releases below 2.2.0 are only running `docker-compose up` that only pull images on the first deployment. If an image changes it ignores the pull policy. To solve this issue is required that `docker-compose pull` runs before `docker-compose up`.
An example of this solution to solve this issue:
https://github.com/stephanlindauer/docker-compose-updater/blob/master/run.sh

Beside this, is also important in docker-compose.yml file to define the pull_policy property:
```
# Since 2020-05-07, the docker-compose spec also defines the "pull_policy" property for a service:
version: '3.7'

services:
  my-service:
    image: someimage/somewhere
    pull_policy: always
```

A reference of this detail would be also important in the documentation.
