### ISSUE TITLE
Allow to make use of the build environment in config.yml

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#29]
To allow things like e.g. making reference to the repo branch for the name of the docker tag:
```
config:
  project_repos:
    repo1:
      url: https://example.org
      branch: devel
      dockerhub: example1/example
      dockertag: $branch
```
