### ISSUE TITLE
Common services definition

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#49]
For common services like database, dataverse, workload managers, they can be automatically added to the Compose agent as available components.
To use this concept, it needs to be defined a special context in config called service that will be added to the compose configuration. They will use available docker images from dockerhub registry. It can be implemented answering to the follow example:

```
config:
  project_repos:
    worsica-processing:
      repo: 'https://github.com/WORSICA/worsica-processing.git'
      branch: master
      dockerhub: worsica/worsica-processing
      dockertag: latest
  services:
    - db1:
        type: postgres
        version: 12.1
        environment:
          - PGPORT: 5432:5432
          - POSTGRES_PASSWORD: ${from_configCredentials1}
    - db2:
        type: postgres
        version: 12.1
        environment:
          - PGPORT: 5432:5432
          - POSTGRES_PASSWORD: ${from_configCredentials2}
    - fair_repo:
        type: dataverse
        version: 4.20
        environment:
          - SOLR_PORT: 8983
          - ADMIN_PORT: 4848
          - API_PORT: 8000
          - PORTAL_PORT:443
          - ADMIN_EMAIL: admin@localhost
          - MAIL_SERVER: mailrelay
          - POSTGRES_ADMIN_PASSWORD: ${from_configCredentials3}
          - POSTGRES_USER: dvnapp
          - RSERVE_PASSWORD: ${from_configCredentials4}

sqa-criteria:
  qc-style:
    repos:
      worsica-processing:
        container: processing
        tox:
          testenv:
            - stylecheck

environment:
  GIT_COMMITTER_NAME: Person1
  GIT_COMMITTER_EMAIL: person1@example.org
  LANG: C.UTF-8

timeout: 600
```

In the previous example the service hostnames would be:
- db1
- db2
- fair_repo

When using config.services this will not be available to run commands or referencing as container in sqa_criteria. The user can use the environment variables to configure the services as defined by referenced images. The environment variables can be defined at two different levels:
- in service scope
- at primary domain

For current Docker Compose Agent is possible to use extends to merge the configurations as overrides or importing multiple configuration files:
https://docs.docker.com/compose/extends/
