### ISSUE TITLE
config:repo needs credentials id from jenkins in case of private repository

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#78]
Add an additional attribute to repository configurations in config section so is possible to checkout from private domain:
```
"config_repo_settings": {
            "type": "object",
            "properties": {
                "repo": { "type": "string", "format": "uri" },
                "branch": { "type": "string" },
                "dockerhub": { "type": "string" },
                "dockertag": {
                    "anyOf": [
                        { "type": "string" },
                        { "type": "array" }
                    ]
                }
                "credentials_id": { "type": "string" },
            },
            "required": ["repo"]
        },
```

**Comment by samuelbernardolip** [comment]
We can avoid an additional attribute in config.yml using for that predefined environment variables.
Those can be set from credentials namespace.

Example:
```
config:
  project_repos:
    sqaaas_web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: jpl-branch
    sqaaas_web2:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: gh-pages
  credentials:
      - id: userpass_sqaaas_web
        username_var: JPL_SQAAAS_WEB_USER
        password_var: JPL_SQAAAS_WEB_PASSWORD
      - id: userpass_sqaaas_web
        username_var: JPL_SQAAAS_WEB2_USER
        password_var: JPL_SQAAAS_WEB2_PASSWORD
```

@orviz This requires that schema be updated to only allow the characters expected in environment variables:
```
"config_repo": {
            "type": "object",
            "minProperties": 1,
            "patternProperties": {
                "[a-z0-9_]*": { "$ref": "#/definitions/config_repo_settings" }
            }
        },
```
